flasktol/answers/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, SubmitField, TextAreaField, IntegerField
from wtforms.validators import DataRequired


class AnswerForm(FlaskForm):
    content = TextAreaField('Answer 答案')
    content_file = FileField('Content File 檔案 (.jpg, .png, .pdf)', validators=[FileAllowed(['jpg', 'png', 'pdf'])])
    submit = SubmitField('Create 建立')


class GradeForm(FlaskForm):
    grade = IntegerField('Grade')
    submit = SubmitField('Save')

flasktol/questions/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, SubmitField, TextAreaField, SelectField, SelectMultipleField, BooleanField
from wtforms.widgets import ListWidget, CheckboxInput
from wtforms.validators import DataRequired

class MultiCheckboxField(SelectMultipleField):
	widget=ListWidget(prefix_label=False)
	option_widget=CheckboxInput()

class QuestionForm(FlaskForm):
    title = StringField('Title 標題', validators=[DataRequired()])
    content = TextAreaField('Description 備註')
    content_file = FileField('Content File 檔案 (.jpg, .png, .pdf)', validators=[FileAllowed(['jpg', 'png', 'pdf'])])
    access = SelectField("Access level 權限", validators=[DataRequired()], choices=[('1', "Guest 一般"), ('2', "Trainee 國手"), ('3', "Admin 管理員")])
    difficulty = SelectField("Difficulty 難易度", validators=[DataRequired()], choices=[('1', "1"), ('2', "2"), ('3', "3"),('4', "4"),('5', "5")])
    tags= MultiCheckboxField("Type 類型", choices=[('Phonology 音素學',"Phonology 音素學"), ('Morphology 構詞學', "Morphology 構詞學"), ('Syntax 語法學', "Syntax 語法學"),('Semantics 語義學',"Semantics 語義學"),('Maths 數學', "Maths 數學"),('Writing systems 文字系統',"Writing systems 文字系統"),('Culture 文化',"Culture 文化"), ('Sociolinguistics 社會語言學',"Sociolinguistics 社會語言學"),('Historical Linguistics 歷史語言學',"Historical Linguistics 歷史語言學"),('Computational linguistics 電腦語言學',"Computational Linguistics 電腦語言學")])
    source = StringField('Source 出處')
    open_solution=BooleanField("Open View Solution 開放檢視答案")
    solution = TextAreaField('Solution 解答')
    solution_file= FileField('Content File 檔案 (.jpg, .png, .pdf)', validators=[FileAllowed(['jpg', 'png', 'pdf'])])
    special_characters=TextAreaField('Special Characters 特殊字元')
    submit = SubmitField("Create 建立")


class UpdateQuestionForm(FlaskForm):
    title = StringField('Title 標題', validators=[DataRequired()])
    content = TextAreaField('Description 備註')
    content_file = FileField('Content File 檔案 (.jpg, .png, .pdf)', validators=[FileAllowed(['jpg', 'png', 'pdf'])])
    access = SelectField("Access level 權限", validators=[DataRequired()], choices=[('1', "Guest 一般"), ('2', "Trainee 國手"), ('3', "Admin 管理員")])
    difficulty = SelectField("Difficulty 難易度", validators=[DataRequired()], choices=[('1', "1"), ('2', "2"), ('3', "3"),('4', "4"),('5', "5")])
    tags= TextAreaField("Type 類型")
    source = StringField('Source 出處')
    open_solution=BooleanField("Open View Solution 開放檢視答案")
    solution = TextAreaField('Solution 解答')
    solution_file = FileField('Content File 檔案 (.jpg, .png, .pdf)', validators=[FileAllowed(['jpg', 'png', 'pdf'])])
    special_characters=TextAreaField('Special Characters 特殊字元')
    submit = SubmitField("Update 更新")

flasktol/answers/routes.py
from flask import Blueprint
from flasktol.models import User, Question, Answer
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flasktol import db
from flasktol.answers.forms import AnswerForm, GradeForm
from flasktol.answers.utils import save_picture, save_pdf
import os
from flasktol import db, bcrypt
from flask import Blueprint
answers = Blueprint('answers', __name__)

# submit new answer (view depends on access)
@answers.route("/answers/new/<int:question_id>", methods=['GET', 'POST'])
@login_required
def new_answer(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    if question.access > 1 and not current_user.is_authenticated:
        abort(403)
    elif current_user.is_authenticated:
        if question.access > current_user.access:
            abort(403)
    if form.validate_on_submit():
        if form.content_file.data:
            _, f_ext = os.path.splitext(form.content_file.data.filename)
            if f_ext == '.pdf':
                content = save_pdf(form.content_file.data)
            else:
                content = save_picture(form.content_file.data)
            answer = Answer(user_id=current_user.id, question_id=question.id, content=form.content.data, content_file=content)
        else:
            answer = Answer(user_id=current_user.id, question_id=question.id, content=form.content.data)
        db.session.add(answer)
        db.session.commit()
        flash("Your answer has been submitted 已送出答案", 'success')
        return redirect(url_for("questions.question", question_id=question.id))
    return render_template("submit_answer.html", title="Submit Answer 答題", form=form, legend="Submit Answer 答題", question=question)


# list of all answers (admin only)
@answers.route("/answer_list")
@login_required
def answer_list():
    if not current_user.is_admin():
        abort(403)
    answerlist = Answer.query.order_by(Answer.date_submitted.desc())
    return render_template('answer_list.html', title="Answer List 答題列表", answerlist=answerlist, legend="Answer List 答題列表")

# my answers (current user only)
@answers.route("/my_answers")
@login_required
def my_answers():
    answerlist = Answer.query.filter_by(user_id=current_user.id).order_by(Answer.date_submitted.desc())
    return render_template('my_answers.html', title="My Answers 我的答案", answerlist=answerlist, legend="My Answers")

# view answer (non-admin can only view their own)
@answers.route("/answer/<int:answer_id>")
@login_required
def answer(answer_id):
    answer = Answer.query.get_or_404(answer_id)
    if not current_user.is_admin() and current_user.id != answer.answerer.id:
        abort(403)
    if answer.content_file:
        content_file = url_for('static', filename='answer_files/' + answer.content_file)
        _, f_ext = os.path.splitext(answer.content_file)
        if f_ext == '.pdf':
            return render_template('answer.html', content_file=content_file, answer=answer, ispdf=True)
        else:
            return render_template('answer.html', content_file=content_file, answer=answer, ispdf=False)
    else:
        return render_template('answer.html', title="Answer 答題",answer=answer, ispdf=False)

# grade answer (admin only)
@answers.route("/answer/grade/<int:answer_id>", methods=['GET', 'POST'])
@login_required
def grade_answer(answer_id):
    if not current_user.is_admin():
        abort(403)
    answer = Answer.query.get_or_404(answer_id)
    form = GradeForm()
    if form.validate_on_submit():
        answer.grade=form.grade.data
        db.session.commit()
        flash("Score has been updated 已更新評分", 'success')
        return redirect(url_for('answers.answer_list'))
    elif request.method == 'GET':
        form.grade.data = answer.grade
    return render_template('grade_answer.html', title="Grade answer 答題評分", form=form, legend="Grade answer 答題評分")

@answers.route("/users_grades")
@login_required
def users_grades():
    if not current_user.is_admin():
        abort(403)
    answerlist = Answer.query.order_by(Answer.date_submitted.desc())
    questionlist = Question.query.all()
    userlist= User.query.all()

    latest_grade = {}
    highest_grade={}
    for answer in answerlist:
        if answer.user_id in latest_grade:
            if answer.question_id in latest_grade[answer.user_id]:
                if answer.grade>highest_grade[answer.user_id][answer.question_id][0]:
                    highest_grade[answer.user_id][answer.question_id]=(answer.grade,answer.id)
            else:
                latest_grade[answer.user_id][answer.question_id]=(answer.grade,answer.id)
                highest_grade[answer.user_id][answer.question_id]=(answer.grade,answer.id)
        else:
            latest_grade[answer.user_id]={answer.question_id:(answer.grade,answer.id)}
            highest_grade[answer.user_id]={answer.question_id:(answer.grade,answer.id)}

    score_sum={}
    for userid, useranswers in highest_grade.items():
        for questionid, useranswer in useranswers.items():
            try:
                score_sum[userid]+=useranswer[0]
            except:
                score_sum[userid]=useranswer[0]

    return render_template('users_grades.html',answerlist=answerlist,questionlist=questionlist,userlist=userlist, latest_grade=latest_grade,highest_grade=highest_grade, score_sum=score_sum, title="Users grades 用戶分數", legend="sers grades 用戶分數")

flasktol/questions/routes.py
from flask import Blueprint, request
from flasktol.models import User, Question, Answer
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flasktol import db
from flasktol.questions.forms import QuestionForm, UpdateQuestionForm
from flasktol.questions.utils import q_save_picture, q_save_pdf,s_save_picture, s_save_pdf
import os
from flasktol import db, bcrypt
questions = Blueprint('questions', __name__)

# add new question (admin only)
@questions.route("/questions/new", methods=['GET', 'POST'])
@login_required
def new_question():
    if not current_user.is_admin():
        abort(403)
    form = QuestionForm()
    if form.validate_on_submit():
        question = Question()
        if form.content_file.data:
            _, f_ext = os.path.splitext(form.content_file.data.filename)
            if f_ext == '.pdf':
                content = q_save_pdf(form.content_file.data)
            else:
                content = q_save_picture(form.content_file.data)
            question.content_file=content
        if form.solution_file.data:
            _, f_ext = os.path.splitext(form.solution_file.data.filename)
            if f_ext == '.pdf':
                content = s_save_pdf(form.solution_file.data)
            else:
                content = s_save_picture(form.solution_file.data)
            question.solution_file=content
        question.title = form.title.data
        question.content = form.content.data
        question.access=int(form.access.data)
        question.difficulty=int(form.difficulty.data)
        question.tags=", ".join(form.tags.data)
        question.source=form.source.data
        question.solution=form.solution.data
        question.special_characters=form.special_characters.data
        question.open_solution=form.open_solution.data
        db.session.add(question)
        db.session.commit()
        flash("Your question has been created 已新增題目", 'success')
        return redirect(url_for('main.home'))
    return render_template("create_question.html", title="New Question 新增題目", form=form, legend="New Question 新增題目")

# list of all questions (view depends on access)
@questions.route("/question_list/<string:sort_type>/<string:a_d_order>")
def question_list(sort_type,a_d_order):
    if a_d_order=="a":
        if sort_type=="id":
            questionlist = Question.query.order_by(Question.id.asc())
        if sort_type=="date":
            questionlist = Question.query.order_by(Question.date_posted.asc())
        if sort_type=="title":
            questionlist = Question.query.order_by(Question.title.asc())
        elif sort_type=="source":
            questionlist = Question.query.order_by(Question.source.asc())
        elif sort_type=="difficulty":
            questionlist = Question.query.order_by(Question.difficulty.asc())
        elif sort_type=="type":
            questionlist = Question.query.order_by(Question.tags.asc())
        elif sort_type=="availability":
            questionlist = Question.query.order_by(Question.access.asc())
    elif a_d_order=="b":
        if sort_type=="id":
            questionlist = Question.query.order_by(Question.id.desc())
        if sort_type=="date":
            questionlist = Question.query.order_by(Question.date_posted.desc())
        if sort_type=="title":
            questionlist = Question.query.order_by(Question.title.desc())
        elif sort_type=="source":
            questionlist = Question.query.order_by(Question.source.desc())
        elif sort_type=="difficulty":
            questionlist = Question.query.order_by(Question.difficulty.desc())
        elif sort_type=="type":
            questionlist = Question.query.order_by(Question.tags.desc())
        elif sort_type=="availability":
            questionlist = Question.query.order_by(Question.access.desc())
    return render_template('question_list.html', title="Question List 題目列表", questionlist=questionlist, legend="Question List 題目列表",sort_type=sort_type,a_d_order=a_d_order)

# question details (view depends on access)
@questions.route("/question/<int:question_id>")
def question(question_id):
    question = Question.query.get_or_404(question_id)
    if question.access > 1 and not current_user.is_authenticated:
        abort(403)
    elif current_user.is_authenticated:
        if question.access > current_user.access:
            abort(403)
    if current_user.is_authenticated:
        if current_user.is_admin():
            answerlist = Answer.query.filter_by(question_id=question.id).order_by(Answer.date_submitted.desc())
        else:
            answerlist = Answer.query.filter_by(question_id=question.id, user_id=current_user.id).order_by(Answer.date_submitted.desc())
    else:
        answerlist = []
    if question.content_file:
        content_file = url_for('static', filename='question_files/' + question.content_file)
        _, f_ext = os.path.splitext(question.content_file)
        if f_ext == '.pdf':
            ispdf=True
        else:
            ispdf=False
    else:
        content_file=None
        ispdf=False
    return render_template('question.html', title=question.title, content_file=content_file, question=question, ispdf=ispdf, answerlist=answerlist)

# update question (admin only)
@questions.route("/question/<int:question_id>/update", methods=['GET', 'POST'])
@login_required
def update_question(question_id):
    question = Question.query.get_or_404(question_id)
    if not current_user.is_admin():
        abort(403)
    form = UpdateQuestionForm()
    if form.validate_on_submit():
        question.title = form.title.data
        question.content = form.content.data
        if form.content_file.data:
            _, f_ext = os.path.splitext(form.content_file.data.filename)
            if f_ext == '.pdf':
                content = q_save_pdf(form.content_file.data)
            else:
                content = q_save_picture(form.content_file.data)
            question.content_file = content
        if form.solution_file.data:
            _, f_ext = os.path.splitext(form.solution_file.data.filename)
            if f_ext == '.pdf':
                content = s_save_pdf(form.solution_file.data)
            else:
                content = s_save_picture(form.solution_file.data)
            question.solution_file = content
        question.access=int(form.access.data)
        question.difficulty=int(form.difficulty.data)
        question.tags=form.tags.data
        question.source=form.source.data
        question.solution=form.solution.data
        question.special_characters=form.special_characters.data
        question.open_solution=form.open_solution.data
        db.session.commit()
        flash("Question has been updated 已更新題目", 'success')
        return redirect(url_for('questions.question', question_id=question.id))
    elif request.method == 'GET':
        form.title.data = question.title
        form.content.data = question.content
        form.tags.data=question.tags
        form.access.process_data(str(question.access))
        form.difficulty.process_data(str(question.difficulty))
        form.open_solution.process_data(str(question.open_solution))
        form.source.data=question.source
        form.solution.data=question.solution
        form.special_characters.data=question.special_characters
    return render_template('update_question.html', title="Update question 更新題目", form=form, legend="Update question 更新題目")

# delete question (admin only)
@questions.route("/question/<int:question_id>/delete", methods=['POST'])
@login_required
def delete_question(question_id):
    question = Question.query.get_or_404(question_id)
    if not current_user.is_admin():
        abort(403)
    answer = Answer.query.filter_by(question_id=question.id).all()
    for ans in answer:
        db.session.delete(ans)
    db.session.delete(question)
    db.session.commit()
    flash("Question has been deleted 已刪除題目", 'success')
    return redirect(url_for('questions.question_list',sort_type="id",a_d_order="b"))

# view solutions (admin only / available to all if question.open_solution is True)
@questions.route("/question/<int:question_id>/solution")
def solution(question_id):
    question = Question.query.get_or_404(question_id)
    if current_user.is_authenticated:
        if not current_user.is_admin() and not question.open_solution:
            abort(403)
    else:
        if not question.open_solution:
            abort(403)
    if question.solution_file:
        solution_file = url_for('static', filename='solution_files/' + question.solution_file)
        _, f_ext = os.path.splitext(question.solution_file)
        if f_ext == '.pdf':
            ispdf=True
        else:
            ispdf=False
    else:
        solution_file=None
        ispdf=False
    return render_template('solution.html', title="View solution 解答", legend="View solution 解答", question=question, solution_file=solution_file, ispdf=ispdf)

flasktol/templates/answer.html
{% extends "layout.html" %}
{% block content %}
	<article class="media content-section">
	  <div class="media-body">
	    <div class="article-metadata">

            <legend class="border-bottom mb-4">{{answer.answerer.username}} -> {{answer.solveq.title}}</legend>
            
		    <p class="article-content">{{ answer.content }}</p>

		    {% if answer.content_file %}
		    	{% if ispdf %}
					<embed src="{{content_file}}" type="application/pdf"   height="500px" width="100%">
		    	{% else %}
		    		<img src="{{content_file}}">
		    	{% endif %}
		    {% endif %}

	  </div>
    <small class="text-muted">Added 新增日期: {{ answer.date_submitted.strftime("%Y-%m-%d %H:%M:%S") }}</small>

</div>
</article>


{% endblock content%}

flasktol/templates/answer_list.html
{% extends "layout.html" %}
{% block content %}
        <article class="media content-section">
            <div class="media-body">
            <legend class='border-bottom mb-4'> Answers 答題列表</legend>
            <table class="table">
              <thead class="thead-dark">
                <tr>
                  <th scope="col">id</th>
                  <th scope="col">Time Submitted<div style="height: 2px;"></div>答題時間</th>
                  <th scope="col">User<div style="height: 2px;"></div>用戶</th>
                  <th scope="col"> Question<div style="height: 2px;"></div>題目</th>
                  <th scope="col"> Grade<div style="height: 2px;"></div>評分</th>
                  <th scope="col"></th>
                </tr>
              </thead>
              <tbody>
                {% for answer in answerlist %}
                      <tr>
                        <td>{{answer.id}}</td>
                        <td><a href='{{url_for("answers.answer", answer_id=answer.id)}}'>{{answer.date_submitted.strftime("%Y-%m-%d %H:%M:%S")}}</a></td>
                        <td><a href='{{url_for("users.account", username=answer.answerer.username)}}'>{{answer.user_id}} - {{answer.answerer.username}}</a></td>
                        <td><a href='{{url_for("questions.question", question_id=answer.question_id)}}'>{{answer.question_id}} - {{answer.solveq.title}}</a></td>
                        <td>{{answer.grade}}</td>
                        <td><a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{url_for('answers.grade_answer',answer_id=answer.id)}}">Grade 評分</a></td>
                      </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </article>
{% endblock content%}

flasktol/templates/question.html
{% extends "layout.html" %}
{% block content %}
	<article class="media content-section">
	  <div class="media-body">
	    <div class="article-metadata">
			<a href="{{url_for('questions.question_list',sort_type='id',a_d_order='b')}}"> < Back to questions 回到題目列表</a>
			<br />
			<br />
            <legend class='border-bottom mb-4'> {{ question.title }}</legend>
		    <p class="article-content">{{ question.content }}</p>

		    {% if question.content_file %}
		    	{% if ispdf %}
					<embed src="{{content_file}}" type="application/pdf"   height="1000px" width="100%">
		    	{% else %}
		    		<img src="{{content_file}}">
		    	{% endif %}
		    {% endif %}

	  </div>
    {% if question.open_solution %}
        <a class="btn btn-success btn-sm mt-1 mb-1" href="{{url_for('questions.solution',question_id=question.id)}}">View Solution<div style="height: 0px;"></div>查看解答</a>
    {% endif %}
    {% if current_user.is_authenticated %}
    			<a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{url_for('answers.new_answer',question_id=question.id)}}">Answer<div style="height: 0px;"></div>答題</a>
      {% if current_user.is_admin() and not question.open_solution %}
          <a class="btn btn-success btn-sm mt-1 mb-1" href="{{url_for('questions.solution',question_id=question.id)}}">View Solution<div style="height: 0px;"></div>查看解答</a>
      {% endif %}
    	{% if current_user.is_admin() %}
    			<a class="btn btn-warning btn-sm mt-1 mb-1" href="{{url_for('questions.update_question',question_id=question.id)}}">Update<div style="height: 0px;"></div>更新</a>
    			<button type="button" class="btn btn-danger btn-sm mt-1 mb-1" data-toggle="modal" data-target="#deleteModal">Delete<div style="height: 0px;"></div>刪除</button>

    	{% endif %}	
    {% endif %}
    <legend class='border-bottom mb-4'> <br/> Answers 回答</legend>
    {% if answerlist==[] %}
      <p class='text-muted'>Log in to answer questions<br/>登入以開始答題 </p>
    {% else %}
      {% for answer in answerlist %}
        <a href="{{url_for('answers.answer',answer_id=answer.id)}}"><p>{{answer.answerer.username}} on {{ answer.date_submitted.strftime("%Y-%m-%d %H:%M:%S") }} </p></a>
      {% endfor %}
    {% endif %}
    <br>
    <div style="height: 0px;"></div>
    <legend class='border-bottom mb-4'></legend>
    <small class="text-muted">Added 新增日期: {{ question.date_posted.strftime("%Y-%m-%d") }}
    <br>Type 類型: {{question.tags}}
    <br>Difficulty 難易度: {{question.difficulty}}</small>

</div>
</article>
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete Question?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <form action="{{url_for('questions.delete_question', question_id=question.id)}}" method="POST">
        	<input class="btn btn-danger" type="submit", value="Delete">
    	</form>
      </div>
    </div>
  </div>
</div>

{% endblock content%}

flasktol/templates/question_list.html
{% extends "layout.html" %}
{% block content %}
        
        <article class="media content-section">
            <div class="media-body">
            <legend class='border-bottom mb-4'> Questions 題目</legend>
              <div class='text-right'>
                {% if a_d_order=="a" %}
                  <a class="btn btn-info btn-sm" href="{{url_for('questions.question_list',sort_type=sort_type,a_d_order='b')}}" role="button">Ascending<div style="height: 2px;"></div>由下至上</a>
                {% else %}
                  <a class="btn btn-info btn-sm" href="{{url_for('questions.question_list',sort_type=sort_type,a_d_order='a')}}" role="button">Descending<div style="height: 2px;"></div>由上至下</a>
                {% endif %}
                <div class="btn-group ">
                  <button type="button" class="btn btn-info dropdown-toggle btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Sort by<div style="height: 2px;"></div>排序
                  </button>
                  <div class="dropdown-menu dropdown-menu-right">
                    <a class="dropdown-item" href="{{url_for('questions.question_list',sort_type='id',a_d_order='a')}}">ID</a>
                    <a class="dropdown-item" href="{{url_for('questions.question_list',sort_type='title',a_d_order='a')}}">Title<div style="height: 2px;"></div>標題</a>
                    <a class="dropdown-item" href="{{url_for('questions.question_list',sort_type='date',a_d_order='a')}}">Date Added<div style="height: 2px;"></div>新增日期</a>
                    <a class="dropdown-item" href="{{url_for('questions.question_list',sort_type='source',a_d_order='a')}}">Source<div style="height: 2px;"></div>出處</a>                    <a class="dropdown-item" href="{{url_for('questions.question_list',sort_type='difficulty',a_d_order='a')}}">Difficulty<div style="height: 2px;"></div>難易度</a>
                    <a class="dropdown-item" href="{{url_for('questions.question_list',sort_type='type',a_d_order='a')}}">Type<div style="height: 2px;"></div>類型</a>
                    <a class="dropdown-item" href="{{url_for('questions.question_list',sort_type='availability',a_d_order='a')}}">Availability<div style="height: 2px;"></div>開放權限</a>
                  </div></div>

              </div>
              <div style="height: 10px;"></div>
              <div class="table-responsive-sm">
                <table class="table">
                <thead class="thead-dark">
                  <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Title<div style="height: 2px;"></div>標題</th>
                    <th scope="col">Date Added<div style="height: 2px;"></div>新增日期</th>
                    <th scope="col">Source<div style="height: 2px;"></div>出處</th>
                    <th scope="col">Difficulty<div style="height: 2px;"></div>難易度</th>
                    <th scope="col" style="width: 30%">Type<div style="height: 2px;"></div>類型</th>
                    <th scope="col">Available to<div style="height: 2px;"></div>開放給...</th>        
                    <th scope="col"></th>
                  </tr>
                </thead>
                <tbody>
                  {% for question in questionlist %}
                    {% if current_user.is_authenticated %}
                      {% if current_user.access>=question.access%}
                        <tr>
                          <th scope="row">{{question.id}}</th>
                          <td><a href='{{url_for("questions.question", question_id=question.id)}}'>{{question.title}}</a></td>
                          <td>{{question.date_posted.strftime("%Y-%m-%d")}}</td>
                          <td>{{question.source}}</td>
                          <td>{{question.difficulty}}</td>
                          <td>{{question.tags}}</td>
                          {% if question.access == 3 %}
                            <td> Admin<div style="height: 2px;"></div>管理員</td>
                            <td><a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{url_for('answers.new_answer',question_id=question.id)}}">Answer 答題</a></td>
                          {% elif question.access == 2 %}
                            <td>Trainee<div style="height: 2px;"></div>國手</td>
                            <td><a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{url_for('answers.new_answer',question_id=question.id)}}">Answer 答題</a></td>
                          {% else %}
                            <td>All<div style="height: 2px;"></div>全部</td>
                            <td><a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{url_for('answers.new_answer',question_id=question.id)}}">Answer 答題</a></td>
                          {% endif %}
                        </tr>
                      {% endif %}
                    {% else %}
                      {% if question.access== 1%}
                        <tr>
                          <th scope="row">{{question.id}}</th>
                          <td><a href='{{url_for("questions.question", question_id=question.id)}}'>{{question.title}}</a></td>
                          <td>{{question.date_posted.strftime("%Y-%m-%d")}}</td>
                          <td>{{question.source}}</td>
                          <td>{{question.difficulty}}</td>
                          <td>{{question.tags}}</td>
                          <td>All<div style="height: 2px;"></div>全部</td>
                        </tr>
                      {% endif %}
                    {% endif %}
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </article>
{% endblock content%}

flasktol/templates/users_grades.html
{% extends "layout.html" %}
{% block content %}

        <article class="media content-section">
          <div class="media-body">
          <legend class='border-bottom mb-4'>Users grades 用戶分數</legend>
            <table class="table">
              <thead class="thead-dark">
                <tr>
                  <th scope="col">User<div style="height: 2px;"></div>用戶</th>
                  {% for question in questionlist%}
                    <th scope="col">{{question.title}}</th>
                  {% endfor %}
                  <th scope="col">Total<div style="height: 2px;"></div>總成績</th>
                </tr>
              </thead>
              <tbody>
                {% for user in userlist%}
                    <tr>
                      <th scope="row">{{user.id}} - {{user.username}} <div style="height: 25px;"></th>
                      {% for question in questionlist %}
                        {% if user.id in highest_grade %}
                          {% if question.id in highest_grade[user.id] %}
                            <td><a href='{{url_for("answers.answer",answer_id=highest_grade[user.id][question.id][1])}}'> Highest 最高:</a> {{highest_grade[user.id][question.id][0]}}
                            <div style="height: 2px;"><a href='{{url_for("answers.answer",answer_id=latest_grade[user.id][question.id][1])}}'>
                            Latest 最新:</a> {{latest_grade[user.id][question.id][0]}}</td>
                          {% else %}
                            <td>Highest 最高: --
                            <div style="height: 2px;">
                            Latest 最新: --</td>
                          {% endif %}
                        {% else %}
                          <td>Highest 最高: --
                          <div style="height: 2px;">
                          Latest 最新: --</td>
                        {% endif %}
                      {% endfor %}
                      <td>{{score_sum[user.id]}}</td>
                    </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </article>
{% endblock content%}